In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('../DATASETS/DRUGS/DRUGS.csv')

In [4]:
df.head()

,Region,DlyCigs11,RiskAlc11,mrjyr,Defect,Rate,TobEst,Tob.P,AlcEst,Alc.P,MrjEst,Mrj.P
0,Darling Downs,20.85,24.85,5.6,CNS_Defects,3.9,0.01611,0.240563,0.22708,0.601602,0.024269,0.129975
1,Gold Coast,14.50,33.00,12.3,CNS_Defects,4.0,0.01611,0.240563,0.22708,0.601602,0.024269,0.129975
2,Mackay,19.65,39.90,10.9,CNS_Defects,3.7,0.01611,0.240563,0.22708,0.601602,0.024269,0.129975
3,Metro South,10.55,28.05,11.4,CNS_Defects,3.7,0.01611,0.240563,0.22708,0.601602,0.024269,0.129975
4,South West,14.65,26.75,7.0,CNS_Defects,4.3,0.01611,0.240563,0.22708,0.601602,0.024269,0.129975

In [3]:
df.describe()

,DlyCigs11,RiskAlc11,mrjyr,Rate,TobEst,Tob.P,AlcEst,Alc.P,MrjEst,Mrj.P
count,880.000000,880.000000,880.0000,818.000000,880.000000,880.000000,880.000000,880.000000,880.000000,880.000000
mean,16.371875,31.525000,10.8250,3.899389,-0.004735,0.518342,-0.207896,0.570791,0.007653,0.388891
std,4.719042,5.038238,3.9749,7.102996,0.017624,0.265536,0.453604,0.295088,0.021500,0.266816
min,7.450000,24.850000,5.5000,0.000000,-0.088633,0.016172,-2.360111,0.022491,-0.042503,0.005868
25%,14.000000,27.950000,6.8000,0.400000,-0.012296,0.315218,-0.403168,0.318400,-0.005987,0.129036
50%,15.500000,29.450000,11.0500,1.100000,-0.001535,0.529642,-0.082851,0.603905,0.006141,0.374219
75%,20.150000,33.600000,12.7000,4.000000,0.005897,0.745817,0.090775,0.821926,0.024850,0.655917
max,23.550000,42.350000,18.6000,54.700000,0.023449,0.959899,0.599453,0.999910,0.053595,0.891654

In [7]:
df.columns

Index(['Region', 'DlyCigs11', 'RiskAlc11', 'mrjyr', 'Defect', 'Rate', 'TobEst',
       'Tob.P', 'AlcEst', 'Alc.P', 'MrjEst', 'Mrj.P'],
      dtype='object')